---
title: Publications
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    author: 
    layout: post
    thumbnail-image: 
    social-image: 
    publication: 
date: 2016-10-02 17:11:00.000000000 Z
url: https://dai-global-developments.com
permalink: "/articles/:title"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
excerpt_separator: |2+



email: your-email@domain.com
exclude:
- ".gitignore"
- gulpfile.js
- package.json
- browser-synsc.js
- ".jekyll-metadata"
- node_modules
description: By freely sharing what we learn, we have built a reputation as thought
  leaders who translate ideas into action and action into results.
destination: "./build"
sass:
  style: compressed
algolia:
  application_id: R7MRY12BR6
  index_name: Publications
